// ─── DATA ────────────────────────────────────────────────────────────────────
const CATEGORIES = [
  { id: "businesses", label: "Businesses", icon: "🏢", count: 2847 },
  { id: "properties", label: "Properties", icon: "🏠", count: 5621 },
  { id: "vehicles", label: "Vehicles", icon: "🚗", count: 3204 },
  { id: "jobs", label: "Jobs", icon: "💼", count: 1893 },
  { id: "services", label: "Services", icon: "🛠️", count: 4102 },
  { id: "electronics", label: "Electronics", icon: "📱", count: 6840 },
  { id: "agriculture", label: "Agriculture", icon: "🌾", count: 1205 },
  { id: "fashion", label: "Fashion", icon: "👗", count: 3917 },
  { id: "education", label: "Education", icon: "📚", count: 892 },
  { id: "healthcare", label: "Healthcare", icon: "🏥", count: 567 },
  { id: "products", label: "Products", icon: "📦", count: 8243 },
  { id: "finance", label: "Finance", icon: "💰", count: 431 },
];

const LOCATIONS = ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Nyeri"];

// ─── 150 LISTINGS (Regular Prices) ──────────────────────────────────────────
const LISTINGS = [
  // ─── BUSINESSES (25) ──────────────────────────────────────────────────────────
  { id: 1, category: "businesses", title: "Supermarket – Westlands", priceLabel: "KES 850K", location: "Westlands, Nairobi", description: "Profitable supermarket with 3 years operation. Good location, loyal customers.", image: "🏪", verified: true, featured: false, views: 842, rating: 4.5, reviews: 23, seller: "James Mwangi", daysAgo: 2, badge: null, tags: ["Profitable", "Good Location"] },
  { id: 2, category: "businesses", title: "Café & Bakery – Karen", priceLabel: "KES 650K", location: "Karen, Nairobi", description: "Popular café with established clientele. Fully equipped kitchen, outdoor seating.", image: "☕", verified: true, featured: false, views: 504, rating: 4.6, reviews: 45, seller: "Grace Wanjiru", daysAgo: 5, badge: null, tags: ["Equipment Included", "High Traffic"] },
  { id: 3, category: "businesses", title: "Hardware Store – Industrial Area", priceLabel: "KES 1.2M", location: "Industrial Area, Nairobi", description: "Hardware store with 4 years operation. Stock worth KES 400K included.", image: "🔨", verified: true, featured: false, views: 390, rating: 4.3, reviews: 18, seller: "Peter Kimani", daysAgo: 10, badge: null, tags: ["Stock Included", "Supplier Network"] },
  { id: 4, category: "businesses", title: "Salon & Spa – Kilimani", priceLabel: "KES 450K", location: "Kilimani, Nairobi", description: "Modern salon with 4 workstations. High-end clientele. Established 2 years.", image: "💇", verified: true, featured: false, views: 456, rating: 4.9, reviews: 67, seller: "Mary Achieng", daysAgo: 3, badge: null, tags: ["High-End", "Loyal Clientele"] },
  { id: 5, category: "businesses", title: "Pharmacy – CBD", priceLabel: "KES 1.1M", location: "CBD, Nairobi", description: "Well-established pharmacy in the city centre. Stock worth KES 500K included.", image: "💊", verified: true, featured: false, views: 641, rating: 4.7, reviews: 34, seller: "Nairobi Pharmacy Ltd", daysAgo: 7, badge: null, tags: ["Stock Included", "Central Location"] },
  { id: 6, category: "businesses", title: "Car Wash – Westlands", priceLabel: "KES 380K", location: "Westlands, Nairobi", description: "Busy car wash with 3 bays. Monthly revenue KES 120K+. Equipment included.", image: "🚗", verified: true, featured: false, views: 267, rating: 4.2, reviews: 45, seller: "CarCare Kenya", daysAgo: 12, badge: null, tags: ["Equipment", "Busy Location"] },
  { id: 7, category: "businesses", title: "Electronics Shop – Mombasa Road", priceLabel: "KES 750K", location: "Mombasa Road, Nairobi", description: "Electronics shop selling phones, TVs, accessories. Stock worth KES 300K.", image: "📱", verified: true, featured: false, views: 234, rating: 4.5, reviews: 23, seller: "Tech World", daysAgo: 8, badge: null, tags: ["Stock Included", "Good Location"] },
  { id: 8, category: "businesses", title: "Laundromat – Kilimani", priceLabel: "KES 280K", location: "Kilimani, Nairobi", description: "Self-service laundromat with 6 machines. Good location near apartments.", image: "🧺", verified: false, featured: false, views: 245, rating: 4.3, reviews: 56, seller: "Clean & Fresh", daysAgo: 6, badge: null, tags: ["Self-Service", "Good Location"] },
  { id: 9, category: "businesses", title: "Restaurant – Ngong Road", priceLabel: "KES 980K", location: "Ngong Road, Nairobi", description: "Popular restaurant serving African cuisine. 40 capacity. Fully equipped.", image: "🍽️", verified: true, featured: false, views: 389, rating: 4.8, reviews: 89, seller: "African Flavours", daysAgo: 4, badge: null, tags: ["Fully Equipped", "Good Reputation"] },
  { id: 10, category: "businesses", title: "Butchery – Umoja", priceLabel: "KES 320K", location: "Umoja, Nairobi", description: "Established butchery with cold room. Good customer base.", image: "🥩", verified: true, featured: false, views: 256, rating: 4.6, reviews: 34, seller: "Fresh Meats", daysAgo: 9, badge: null, tags: ["Cold Room", "Established"] },
  { id: 11, category: "businesses", title: "Printing Shop – CBD", priceLabel: "KES 550K", location: "CBD, Nairobi", description: "Full-service printing business. Equipment included. Good cash flow.", image: "🖨️", verified: true, featured: false, views: 134, rating: 4.4, reviews: 28, seller: "PrintPro Kenya", daysAgo: 15, badge: null, tags: ["Equipment", "Good Cash Flow"] },
  { id: 12, category: "businesses", title: "Catering Business – Nairobi", priceLabel: "KES 480K", location: "Nairobi Wide", description: "Established catering business. Kitchen equipment and client base included.", image: "🍳", verified: true, featured: false, views: 145, rating: 4.7, reviews: 56, seller: "Catering Solutions", daysAgo: 11, badge: null, tags: ["Equipment", "Client Base"] },
  { id: 13, category: "businesses", title: "Furniture Store – Thika Road", priceLabel: "KES 890K", location: "Thika Road, Nairobi", description: "Furniture store with showroom and workshop. Stock included.", image: "🪑", verified: true, featured: false, views: 234, rating: 4.5, reviews: 34, seller: "Thika Furniture", daysAgo: 13, badge: null, tags: ["Showroom", "Workshop"] },
  { id: 14, category: "businesses", title: "Electronic Repair – Kenyatta", priceLabel: "KES 210K", location: "Kenyatta Market, Nairobi", description: "Busy electronic repair shop. Phones, laptops, TVs.", image: "🔧", verified: false, featured: false, views: 156, rating: 4.3, reviews: 67, seller: "FixIt Electronics", daysAgo: 4, badge: null, tags: ["Busy", "Good Location"] },
  { id: 15, category: "businesses", title: "Bar & Lounge – Westlands", priceLabel: "KES 1.5M", location: "Westlands, Nairobi", description: "Popular bar and lounge. 3 years operation. Equipment and licenses included.", image: "🍺", verified: true, featured: false, views: 278, rating: 4.9, reviews: 45, seller: "Westlands Lounge", daysAgo: 2, badge: "Featured", tags: ["Licenses", "Equipment"] },
  { id: 16, category: "businesses", title: "Beauty Salon – Mombasa Road", priceLabel: "KES 250K", location: "Mombasa Road, Nairobi", description: "Beauty salon with 3 workstations. Loyal customers.", image: "💄", verified: true, featured: false, views: 134, rating: 4.6, reviews: 56, seller: "Beauty Hub", daysAgo: 6, badge: null, tags: ["Loyal Customers", "Good Location"] },
  { id: 17, category: "businesses", title: "Bakery – Eastleigh", priceLabel: "KES 620K", location: "Eastleigh, Nairobi", description: "Established bakery. Equipment included. Good customer base.", image: "🍞", verified: true, featured: false, views: 145, rating: 4.4, reviews: 34, seller: "Eastleigh Bakery", daysAgo: 8, badge: null, tags: ["Equipment", "Customer Base"] },
  { id: 18, category: "businesses", title: "Travel Agency – CBD", priceLabel: "KES 780K", location: "CBD, Nairobi", description: "Travel agency with IATA license. Good corporate clientele.", image: "✈️", verified: true, featured: false, views: 134, rating: 4.7, reviews: 23, seller: "TravelPro Kenya", daysAgo: 10, badge: null, tags: ["IATA Licensed", "Corporate"] },
  { id: 19, category: "businesses", title: "Gym – Kilimani", priceLabel: "KES 980K", location: "Kilimani, Nairobi", description: "Fully equipped gym with 150+ members. Equipment included.", image: "🏋️", verified: true, featured: false, views: 256, rating: 4.8, reviews: 78, seller: "Fitness Hub", daysAgo: 3, badge: null, tags: ["Equipment", "Members"] },
  { id: 20, category: "businesses", title: "Stationery Shop – Thika", priceLabel: "KES 340K", location: "Thika, Kiambu", description: "Established stationery shop. Stock included. Good location near schools.", image: "📎", verified: true, featured: false, views: 134, rating: 4.3, reviews: 23, seller: "Thika Stationery", daysAgo: 9, badge: null, tags: ["Stock", "Good Location"] },
  { id: 21, category: "businesses", title: "Florist – Karen", priceLabel: "KES 280K", location: "Karen, Nairobi", description: "Beautiful florist shop with loyal customers.", image: "🌸", verified: true, featured: false, views: 134, rating: 4.7, reviews: 34, seller: "Karen Flowers", daysAgo: 5, badge: null, tags: ["Good Location", "Loyal Customers"] },
  { id: 22, category: "businesses", title: "Spare Parts – Industrial Area", priceLabel: "KES 680K", location: "Industrial Area, Nairobi", description: "Spare parts shop with good stock and customer base.", image: "🔩", verified: true, featured: false, views: 134, rating: 4.4, reviews: 23, seller: "SparePro", daysAgo: 11, badge: null, tags: ["Supplier Network", "Stock"] },
  { id: 23, category: "businesses", title: "Ice Cream Parlour – Mombasa", priceLabel: "KES 450K", location: "Mombasa, Mombasa", description: "Popular ice cream parlour near the beach. Equipment included.", image: "🍦", verified: true, featured: false, views: 256, rating: 4.6, reviews: 56, seller: "Beach Ice Cream", daysAgo: 4, badge: null, tags: ["Equipment", "Beach Location"] },
  { id: 24, category: "businesses", title: "Tyre Shop – Nakuru", priceLabel: "KES 480K", location: "Nakuru, Nakuru", description: "Tyre fitting and sales shop. Equipment included.", image: "🛞", verified: true, featured: false, views: 134, rating: 4.3, reviews: 23, seller: "Nakuru Tyres", daysAgo: 12, badge: null, tags: ["Equipment", "Good Location"] },
  { id: 25, category: "businesses", title: "Language School – Westlands", priceLabel: "KES 720K", location: "Westlands, Nairobi", description: "Language school with 60+ students. Teaching English, French.", image: "📖", verified: true, featured: false, views: 134, rating: 4.8, reviews: 34, seller: "Language Hub", daysAgo: 6, badge: null, tags: ["Established", "Good Reputation"] },
  // ─── PROPERTIES (25) ──────────────────────────────────────────────────────────
  { id: 26, category: "properties", title: "3BR Apartment – Kilimani", priceLabel: "KES 4.5M", location: "Kilimani, Nairobi", description: "Modern 3-bedroom apartment, 110sqm, fitted kitchen, parking.", image: "🏢", verified: true, featured: false, views: 1201, rating: 4.9, reviews: 41, seller: "Nairobi Realty Group", daysAgo: 1, badge: "Hot", tags: ["En-suite", "Parking"] },
  { id: 27, category: "properties", title: "4BR Mansion – Runda", priceLabel: "KES 12M", location: "Runda, Nairobi", description: "Spacious 4-bedroom mansion on 0.5 acre. Garden, pool.", image: "🏘️", verified: true, featured: false, views: 841, rating: 4.7, reviews: 34, seller: "Runda Properties", daysAgo: 7, badge: null, tags: ["Gated", "Pool"] },
  { id: 28, category: "properties", title: "Land 2.5 Acres – Kitengela", priceLabel: "KES 3.2M", location: "Kitengela, Kajiado", description: "Prime development land with title deed. Near new highway.", image: "🌅", verified: true, featured: false, views: 692, rating: 4.5, reviews: 12, seller: "Kajiado Land Agency", daysAgo: 4, badge: null, tags: ["Title Deed", "Prime Location"] },
  { id: 29, category: "properties", title: "Studio – CBD", priceLabel: "KES 1.8M", location: "CBD, Nairobi", description: "Modern studio apartment, 35sqm, fully furnished.", image: "🏢", verified: false, featured: false, views: 567, rating: 4.2, reviews: 28, seller: "City Properties", daysAgo: 9, badge: null, tags: ["Central", "Furnished"] },
  { id: 30, category: "properties", title: "Commercial Building – Mombasa Road", priceLabel: "KES 18M", location: "Mombasa Road, Nairobi", description: "Commercial building with shops and offices. 8 tenants.", image: "🏗️", verified: true, featured: false, views: 456, rating: 4.8, reviews: 15, seller: "Prime Properties", daysAgo: 3, badge: "Featured", tags: ["Commercial", "Good Returns"] },
  { id: 31, category: "properties", title: "Land 10 Acres – Naivasha", priceLabel: "KES 4.2M", location: "Naivasha, Nakuru", description: "10 acres of land near Lake Naivasha. Great for agriculture.", image: "🌾", verified: true, featured: false, views: 367, rating: 4.6, reviews: 11, seller: "Naivasha Lands", daysAgo: 11, badge: null, tags: ["Title Deed", "Lake View"] },
  { id: 32, category: "properties", title: "2BR Bungalow – Nakuru", priceLabel: "KES 2.5M", location: "Nakuru, Nakuru", description: "Cosy 2-bedroom bungalow with garden. Quiet neighborhood.", image: "🏡", verified: true, featured: false, views: 234, rating: 4.4, reviews: 8, seller: "Nakuru Homes", daysAgo: 5, badge: null, tags: ["Garden", "Quiet"] },
  { id: 33, category: "properties", title: "Warehouse – Industrial Area", priceLabel: "KES 5.8M", location: "Industrial Area, Nairobi", description: "Warehouse 500sqm with office space. Good for manufacturing.", image: "🏭", verified: true, featured: false, views: 345, rating: 4.3, reviews: 6, seller: "Industrial Spaces", daysAgo: 14, badge: null, tags: ["Large Space", "Office"] },
  { id: 34, category: "properties", title: "Beachfront Villa – Diani", priceLabel: "KES 8.5M", location: "Diani, Kwale", description: "Luxury 4-bedroom villa on Diani beach. Private pool.", image: "🏖️", verified: true, featured: false, views: 678, rating: 5.0, reviews: 23, seller: "Diani Property Group", daysAgo: 2, badge: "Featured", tags: ["Beachfront", "Pool"] },
  { id: 35, category: "properties", title: "Land 1 Acre – Karen", priceLabel: "KES 4.8M", location: "Karen, Nairobi", description: "Prime 1-acre plot in Karen. Ready for construction.", image: "🌳", verified: true, featured: false, views: 456, rating: 4.7, reviews: 9, seller: "Karen Land Agency", daysAgo: 8, badge: null, tags: ["Prime Location", "Ready to Build"] },
  { id: 36, category: "properties", title: "3BR Townhouse – Riverside", priceLabel: "KES 6.2M", location: "Riverside, Nairobi", description: "Modern townhouse in gated community. 2 parking spaces.", image: "🏠", verified: true, featured: false, views: 456, rating: 4.6, reviews: 12, seller: "Riverside Properties", daysAgo: 6, badge: null, tags: ["Gated", "Parking"] },
  { id: 37, category: "properties", title: "Land 5 Acres – Thika", priceLabel: "KES 1.8M", location: "Thika, Kiambu", description: "Agricultural land in Thika. Good soil. Water access.", image: "🌾", verified: true, featured: false, views: 234, rating: 4.4, reviews: 7, seller: "Thika Lands", daysAgo: 9, badge: null, tags: ["Agricultural", "Water Access"] },
  { id: 38, category: "properties", title: "2BR Apartment – Mombasa", priceLabel: "KES 3.2M", location: "Mombasa, Mombasa", description: "2-bedroom apartment with ocean views. 80sqm.", image: "🏢", verified: true, featured: false, views: 234, rating: 4.3, reviews: 9, seller: "Mombasa Realty", daysAgo: 7, badge: null, tags: ["Ocean View", "Well Maintained"] },
  { id: 39, category: "properties", title: "Commercial Land – Kitengela", priceLabel: "KES 2.8M", location: "Kitengela, Kajiado", description: "Commercial land. 1 acre. Near highway. Good for business.", image: "🏗️", verified: true, featured: false, views: 234, rating: 4.5, reviews: 6, seller: "Kitengela Lands", daysAgo: 10, badge: null, tags: ["Commercial", "Highway Access"] },
  { id: 40, category: "properties", title: "4BR House – Nakuru", priceLabel: "KES 3.5M", location: "Nakuru, Nakuru", description: "Spacious 4-bedroom house with garden. Quiet neighborhood.", image: "🏡", verified: true, featured: false, views: 234, rating: 4.6, reviews: 8, seller: "Nakuru Homes", daysAgo: 11, badge: null, tags: ["Garden", "Quiet"] },
  { id: 41, category: "properties", title: "Studio – Westlands", priceLabel: "KES 2.2M", location: "Westlands, Nairobi", description: "Modern studio apartment. 40sqm. Fully furnished.", image: "🏢", verified: true, featured: false, views: 345, rating: 4.4, reviews: 15, seller: "Westlands Realty", daysAgo: 5, badge: null, tags: ["Furnished", "Good Investment"] },
  { id: 42, category: "properties", title: "Land 2 Acres – Kiambu", priceLabel: "KES 1.2M", location: "Kiambu, Kiambu", description: "2-acre land. Good for farming or residential.", image: "🌳", verified: true, featured: false, views: 234, rating: 4.3, reviews: 6, seller: "Kiambu Lands", daysAgo: 12, badge: null, tags: ["Farming", "Residential"] },
  { id: 43, category: "properties", title: "3BR Penthouse – Westlands", priceLabel: "KES 8.5M", location: "Westlands, Nairobi", description: "Luxury penthouse. 180sqm. Amazing views. Rooftop terrace.", image: "🏢", verified: true, featured: false, views: 456, rating: 4.9, reviews: 23, seller: "Luxury Properties", daysAgo: 2, badge: "Featured", tags: ["Penthouse", "Rooftop"] },
  { id: 44, category: "properties", title: "Agricultural Land – Eldoret", priceLabel: "KES 980K", location: "Eldoret, Uasin Gishu", description: "5-acre agricultural land. Good soil. Ideal for farming.", image: "🌾", verified: true, featured: false, views: 234, rating: 4.5, reviews: 7, seller: "Eldoret Lands", daysAgo: 8, badge: null, tags: ["Farming", "Good Soil"] },
  { id: 45, category: "properties", title: "2BR Apartment – Karen", priceLabel: "KES 4.2M", location: "Karen, Nairobi", description: "2-bedroom apartment in Karen. 85sqm. Well maintained.", image: "🏢", verified: true, featured: false, views: 234, rating: 4.5, reviews: 12, seller: "Karen Realty", daysAgo: 6, badge: null, tags: ["Good Security", "Well Maintained"] },
  { id: 46, category: "properties", title: "Commercial Plot – Mombasa", priceLabel: "KES 4.5M", location: "Mombasa, Mombasa", description: "Commercial plot. 0.5 acre. Good for development.", image: "🏗️", verified: true, featured: false, views: 234, rating: 4.6, reviews: 8, seller: "Mombasa Lands", daysAgo: 9, badge: null, tags: ["Commercial", "Development"] },
  { id: 47, category: "properties", title: "4BR Villa – Runda", priceLabel: "KES 14M", location: "Runda, Nairobi", description: "Luxury 4-bedroom villa. Pool, garden, staff quarters.", image: "🏘️", verified: true, featured: false, views: 456, rating: 4.8, reviews: 15, seller: "Runda Luxury", daysAgo: 3, badge: null, tags: ["Luxury", "Pool"] },
  { id: 48, category: "properties", title: "Land 8 Acres – Nanyuki", priceLabel: "KES 2.8M", location: "Nanyuki, Laikipia", description: "8-acre land. Good for farming or development.", image: "🌄", verified: true, featured: false, views: 234, rating: 4.4, reviews: 6, seller: "Nanyuki Lands", daysAgo: 10, badge: null, tags: ["Farming", "Development"] },
  { id: 49, category: "properties", title: "Studio – Kilimani", priceLabel: "KES 2.0M", location: "Kilimani, Nairobi", description: "Modern studio apartment. 38sqm. Good investment.", image: "🏢", verified: true, featured: false, views: 234, rating: 4.3, reviews: 12, seller: "Kilimani Realty", daysAgo: 7, badge: null, tags: ["Investment", "Good Location"] },
  { id: 50, category: "properties", title: "Beachfront Land – Diani", priceLabel: "KES 5.5M", location: "Diani, Kwale", description: "Prime beachfront land. 2 acres. Good for resort.", image: "🏖️", verified: true, featured: false, views: 456, rating: 4.9, reviews: 12, seller: "Diani Beach Properties", daysAgo: 2, badge: "Featured", tags: ["Beachfront", "Resort"] },
  // ─── VEHICLES (20) ────────────────────────────────────────────────────────────
  { id: 51, category: "vehicles", title: "Toyota Land Cruiser V8 2019", priceLabel: "KES 3.2M", location: "Karen, Nairobi", description: "Single owner, full service history. Pearl white, leather interior.", image: "🚙", verified: true, featured: false, views: 892, rating: 4.7, reviews: 12, seller: "AutoKe Premium", daysAgo: 3, badge: null, tags: ["Single Owner", "Full History"] },
  { id: 52, category: "vehicles", title: "Toyota Hilux Double Cab 2021", priceLabel: "KES 2.8M", location: "Thika, Kiambu", description: "Low mileage 35,000km. 4x4, automatic. Perfect for business.", image: "🚛", verified: true, featured: false, views: 1345, rating: 4.8, reviews: 23, seller: "Hilux Motors", daysAgo: 6, badge: null, tags: ["Low Mileage", "4x4"] },
  { id: 53, category: "vehicles", title: "Nissan X-Trail 2020", priceLabel: "KES 2.2M", location: "Nakuru, Nakuru", description: "Well maintained SUV. One owner. 7-seater.", image: "🚗", verified: true, featured: false, views: 567, rating: 4.5, reviews: 34, seller: "Nakuru Auto Centre", daysAgo: 11, badge: null, tags: ["7-Seater", "Well Maintained"] },
  { id: 54, category: "vehicles", title: "Motorcycle – Boxer BM150", priceLabel: "KES 65K", location: "Kisumu, Kisumu", description: "2022 model. Low mileage. Perfect for delivery.", image: "🏍️", verified: false, featured: false, views: 392, rating: 4.3, reviews: 45, seller: "Kisumu Motors", daysAgo: 8, badge: null, tags: ["Low Mileage", "Good Condition"] },
  { id: 55, category: "vehicles", title: "Mercedes Benz E200 2018", priceLabel: "KES 2.5M", location: "Westlands, Nairobi", description: "Elegant Mercedes E200. Full service history.", image: "🚘", verified: true, featured: false, views: 678, rating: 4.6, reviews: 18, seller: "Luxury Auto", daysAgo: 5, badge: null, tags: ["Luxury", "Well Maintained"] },
  { id: 56, category: "vehicles", title: "Toyota Sienta 2020", priceLabel: "KES 1.8M", location: "Mombasa, Mombasa", description: "Family-friendly 7-seater. Good condition. Low mileage.", image: "🚐", verified: true, featured: false, views: 234, rating: 4.4, reviews: 12, seller: "Mombasa Autos", daysAgo: 9, badge: null, tags: ["7-Seater", "Family"] },
  { id: 57, category: "vehicles", title: "Isuzu D-Max 2021", priceLabel: "KES 2.6M", location: "Thika, Kiambu", description: "Double cab pick-up. 4x4, diesel. 30,000km.", image: "🚜", verified: true, featured: false, views: 345, rating: 4.7, reviews: 15, seller: "Pickup Kenya", daysAgo: 4, badge: null, tags: ["Double Cab", "4x4"] },
  { id: 58, category: "vehicles", title: "VW Polo Vivo 2019", priceLabel: "KES 1.2M", location: "CBD, Nairobi", description: "Well-maintained VW Polo. 40,000km. Perfect for city.", image: "🚗", verified: false, featured: false, views: 456, rating: 4.2, reviews: 8, seller: "City Cars", daysAgo: 12, badge: null, tags: ["City", "Good Condition"] },
  { id: 59, category: "vehicles", title: "Toyota Prado TX 2017", priceLabel: "KES 2.9M", location: "Karen, Nairobi", description: "Well maintained Prado. 4x4. 60,000km.", image: "🚙", verified: true, featured: false, views: 456, rating: 4.6, reviews: 14, seller: "Prado Auto", daysAgo: 6, badge: null, tags: ["4x4", "Good Condition"] },
  { id: 60, category: "vehicles", title: "Honda Fit 2021", priceLabel: "KES 1.5M", location: "Nairobi", description: "Honda Fit in good condition. 35,000km. Fuel efficient.", image: "🚗", verified: true, featured: false, views: 234, rating: 4.4, reviews: 12, seller: "City Autos", daysAgo: 8, badge: null, tags: ["Fuel Efficient", "Good Condition"] },
  { id: 61, category: "vehicles", title: "Mitsubishi Lancer 2018", priceLabel: "KES 1.3M", location: "Mombasa, Mombasa", description: "Mitsubishi Lancer. Good condition. Full service history.", image: "🚗", verified: true, featured: false, views: 234, rating: 4.3, reviews: 9, seller: "Mombasa Motors", daysAgo: 10, badge: null, tags: ["Full History", "Good Condition"] },
  { id: 62, category: "vehicles", title: "Toyota Vitz 2022", priceLabel: "KES 1.1M", location: "Nakuru, Nakuru", description: "Toyota Vitz. Low mileage. Good for city driving.", image: "🚗", verified: true, featured: false, views: 234, rating: 4.5, reviews: 12, seller: "Nakuru Autos", daysAgo: 7, badge: null, tags: ["City", "Low Mileage"] },
  { id: 63, category: "vehicles", title: "Range Rover Sport 2020", priceLabel: "KES 4.5M", location: "Westlands, Nairobi", description: "Luxury Range Rover Sport. 40,000km. Full history.", image: "🚙", verified: true, featured: false, views: 456, rating: 4.8, reviews: 23, seller: "Luxury Motors", daysAgo: 2, badge: "Featured", tags: ["Luxury", "Full History"] },
  { id: 64, category: "vehicles", title: "Toyota Harrier 2019", priceLabel: "KES 2.3M", location: "Nairobi", description: "Toyota Harrier. Good condition. 45,000km.", image: "🚗", verified: true, featured: false, views: 345, rating: 4.5, reviews: 15, seller: "Harrier Autos", daysAgo: 5, badge: null, tags: ["Family", "Well Maintained"] },
  { id: 65, category: "vehicles", title: "Motorcycle – TVS Apache 2023", priceLabel: "KES 120K", location: "Kisumu, Kisumu", description: "2023 TVS Apache. Low mileage. Good condition.", image: "🏍️", verified: false, featured: false, views: 234, rating: 4.2, reviews: 12, seller: "Kisumu Motors", daysAgo: 4, badge: null, tags: ["Low Mileage", "Good Condition"] },
  { id: 66, category: "vehicles", title: "Toyota Hiace 2021", priceLabel: "KES 1.9M", location: "Nairobi", description: "Toyota Hiace van. Good for shuttle business. 12-seater.", image: "🚐", verified: true, featured: false, views: 234, rating: 4.3, reviews: 8, seller: "Shuttle Kenya", daysAgo: 6, badge: null, tags: ["Shuttle", "12-Seater"] },
  { id: 67, category: "vehicles", title: "Subaru Forester 2020", priceLabel: "KES 2.1M", location: "Nakuru, Nakuru", description: "Subaru Forester. Good condition. 50,000km.", image: "🚗", verified: true, featured: false, views: 234, rating: 4.6, reviews: 12, seller: "Nakuru Autos", daysAgo: 5, badge: null, tags: ["SUV", "Good Condition"] },
  { id: 68, category: "vehicles", title: "Audi A4 2019", priceLabel: "KES 2.8M", location: "Westlands, Nairobi", description: "Audi A4. Elegant, well maintained. Full service history.", image: "🚘", verified: true, featured: false, views: 234, rating: 4.7, reviews: 10, seller: "Luxury Cars", daysAgo: 4, badge: null, tags: ["Luxury", "Full History"] },
  { id: 69, category: "vehicles", title: "Toyota Corolla 2022", priceLabel: "KES 1.6M", location: "CBD, Nairobi", description: "Toyota Corolla. Low mileage. Good for city driving.", image: "🚗", verified: true, featured: false, views: 234, rating: 4.4, reviews: 15, seller: "City Autos", daysAgo: 3, badge: null, tags: ["City", "Fuel Efficient"] },
  { id: 70, category: "vehicles", title: "Nissan Note 2021", priceLabel: "KES 1.4M", location: "Mombasa, Mombasa", description: "Nissan Note. Good condition. 30,000km.", image: "🚗", verified: true, featured: false, views: 234, rating: 4.3, reviews: 9, seller: "Mombasa Motors", daysAgo: 7, badge: null, tags: ["Good Condition", "Low Mileage"] },
  // ─── JOBS (15) ─────────────────────────────────────────────────────────────────
  { id: 71, category: "jobs", title: "Senior Software Engineer", priceLabel: "KES 180K/mo", location: "CBD, Nairobi", description: "Fintech seeking Senior Engineer. React, Node.js, Python.", image: "💻", verified: true, featured: false, views: 1145, rating: 5.0, reviews: 8, seller: "PesaPulse Kenya", daysAgo: 0, badge: "Urgent", tags: ["Remote OK", "Equity"] },
  { id: 72, category: "jobs", title: "Sales Manager – FMCG", priceLabel: "KES 120K/mo", location: "Mombasa Road, Nairobi", description: "FMCG company seeking Sales Manager. 8+ years experience.", image: "📊", verified: true, featured: false, views: 642, rating: 4.4, reviews: 6, seller: "Global Brands", daysAgo: 3, badge: null, tags: ["FMCG", "Managerial"] },
  { id: 73, category: "jobs", title: "Registered Nurse – Hospital", priceLabel: "KES 80K/mo", location: "Westlands, Nairobi", description: "Seeking experienced RN for specialized unit. 3+ years.", image: "🏥", verified: true, featured: false, views: 841, rating: 4.6, reviews: 12, seller: "Aga Khan Hospital", daysAgo: 5, badge: "New", tags: ["ICU Experience", "Full Benefits"] },
  { id: 74, category: "jobs", title: "Digital Marketing Specialist", priceLabel: "KES 65K/mo", location: "Karen, Nairobi", description: "E-commerce startup seeking digital marketing specialist.", image: "📱", verified: true, featured: false, views: 489, rating: 4.2, reviews: 9, seller: "ShopAfrica", daysAgo: 7, badge: null, tags: ["SEO", "PPC"] },
  { id: 75, category: "jobs", title: "Accountant – Manufacturing", priceLabel: "KES 70K/mo", location: "Industrial Area, Nairobi", description: "Manufacturing company seeking Accountant. CPA required.", image: "📊", verified: true, featured: false, views: 267, rating: 4.3, reviews: 7, seller: "Manufacturing Ltd", daysAgo: 8, badge: null, tags: ["CPA", "Full Time"] },
  { id: 76, category: "jobs", title: "Construction Project Manager", priceLabel: "KES 110K/mo", location: "Nairobi Wide", description: "Seeking Project Manager for construction projects.", image: "🏗️", verified: true, featured: false, views: 234, rating: 4.5, reviews: 5, seller: "BuildCo Kenya", daysAgo: 10, badge: null, tags: ["Construction", "Managerial"] },
  { id: 77, category: "jobs", title: "Customer Service Manager", priceLabel: "KES 60K/mo", location: "Mombasa, Mombasa", description: "Telecom company seeking Customer Service Manager.", image: "📞", verified: true, featured: false, views: 345, rating: 4.1, reviews: 6, seller: "Telecom Kenya", daysAgo: 6, badge: null, tags: ["Telecom", "Managerial"] },
  { id: 78, category: "jobs", title: "Graphic Designer", priceLabel: "KES 55K/mo", location: "Westlands, Nairobi", description: "Creative agency seeking Graphic Designer. Adobe Suite.", image: "🎨", verified: true, featured: false, views: 456, rating: 4.4, reviews: 8, seller: "Creative Hub", daysAgo: 4, badge: null, tags: ["Adobe Suite", "Creative"] },
  { id: 79, category: "jobs", title: "Supply Chain Manager", priceLabel: "KES 90K/mo", location: "Mombasa Road, Nairobi", description: "Retail company seeking Supply Chain Manager. 5+ years.", image: "📦", verified: true, featured: false, views: 234, rating: 4.5, reviews: 6, seller: "Retail Kenya", daysAgo: 5, badge: null, tags: ["Supply Chain", "Managerial"] },
  { id: 80, category: "jobs", title: "Financial Analyst", priceLabel: "KES 75K/mo", location: "CBD, Nairobi", description: "Investment firm seeking Financial Analyst. CFA preferred.", image: "📈", verified: true, featured: false, views: 234, rating: 4.6, reviews: 7, seller: "Investment Kenya", daysAgo: 6, badge: null, tags: ["CFA", "Investment"] },
  { id: 81, category: "jobs", title: "HR Manager", priceLabel: "KES 85K/mo", location: "Nairobi", description: "HR Manager for growing tech company. 5+ years.", image: "👥", verified: true, featured: false, views: 234, rating: 4.4, reviews: 5, seller: "Tech HR", daysAgo: 7, badge: null, tags: ["HR", "Managerial"] },
  { id: 82, category: "jobs", title: "Content Writer", priceLabel: "KES 45K/mo", location: "Nairobi (Remote)", description: "Seeking content writer for tech blog. 2+ years.", image: "✍️", verified: true, featured: false, views: 234, rating: 4.3, reviews: 12, seller: "Tech Blog", daysAgo: 3, badge: null, tags: ["Remote", "Writing"] },
  { id: 83, category: "jobs", title: "Systems Administrator", priceLabel: "KES 65K/mo", location: "Westlands, Nairobi", description: "Systems Administrator for corporate network.", image: "🖥️", verified: true, featured: false, views: 234, rating: 4.5, reviews: 6, seller: "Corporate Tech", daysAgo: 5, badge: null, tags: ["Systems", "Network"] },
  { id: 84, category: "jobs", title: "Business Development Manager", priceLabel: "KES 95K/mo", location: "Nairobi", description: "BDM for logistics company. 5+ years experience.", image: "📊", verified: true, featured: false, views: 234, rating: 4.6, reviews: 5, seller: "Logistics Kenya", daysAgo: 6, badge: null, tags: ["BDM", "Logistics"] },
  { id: 85, category: "jobs", title: "Data Scientist", priceLabel: "KES 100K/mo", location: "CBD, Nairobi", description: "Data Scientist for Fintech company. Python, ML.", image: "📊", verified: true, featured: false, views: 234, rating: 4.7, reviews: 8, seller: "Data Fintech", daysAgo: 4, badge: null, tags: ["Python", "ML"] },
  // ─── SERVICES (20) ────────────────────────────────────────────────────────────
  { id: 86, category: "services", title: "Web Design & Development", priceLabel: "From KES 15K", location: "Nairobi (Remote)", description: "Premium websites, e-commerce stores. 5+ years experience.", image: "🎨", verified: true, featured: false, views: 674, rating: 4.6, reviews: 89, seller: "TizianTech Edge", daysAgo: 5, badge: null, tags: ["E-commerce", "SEO"] },
  { id: 87, category: "services", title: "Cleaning Services", priceLabel: "From KES 3K", location: "Nairobi Wide", description: "Commercial and residential cleaning. Professional team.", image: "🧹", verified: true, featured: false, views: 456, rating: 4.8, reviews: 156, seller: "CleanKenya", daysAgo: 2, badge: null, tags: ["Commercial", "Residential"] },
  { id: 88, category: "services", title: "Photography & Videography", priceLabel: "From KES 10K", location: "Nairobi & Rift Valley", description: "Professional photography for events, weddings, corporate.", image: "📷", verified: true, featured: false, views: 234, rating: 4.9, reviews: 67, seller: "Lens Academy", daysAgo: 8, badge: null, tags: ["Events", "Wedding"] },
  { id: 89, category: "services", title: "IT Support & Networking", priceLabel: "From KES 5K", location: "Nairobi (Remote/On-site)", description: "IT support, network installation, cybersecurity.", image: "🖥️", verified: true, featured: false, views: 567, rating: 4.4, reviews: 34, seller: "TechFix Kenya", daysAgo: 12, badge: null, tags: ["24/7 Support", "Cybersecurity"] },
  { id: 90, category: "services", title: "Accounting & Tax Services", priceLabel: "From KES 8K", location: "Nairobi (Remote)", description: "Accounting, bookkeeping, tax services. KRA compliant.", image: "🧾", verified: true, featured: false, views: 345, rating: 4.7, reviews: 45, seller: "TaxPro Kenya", daysAgo: 6, badge: null, tags: ["KRA", "QuickBooks"] },
  { id: 91, category: "services", title: "Legal Services – Business Law", priceLabel: "From KES 12K", location: "CBD, Nairobi", description: "Business legal services. Company registration, contracts.", image: "⚖️", verified: true, featured: false, views: 234, rating: 4.9, reviews: 23, seller: "LegalAdvice KE", daysAgo: 9, badge: null, tags: ["Business Law", "Contracts"] },
  { id: 92, category: "services", title: "Plumbing & Electrical", priceLabel: "From KES 2K", location: "Nairobi Wide", description: "Professional plumbing and electrical services. Licensed.", image: "🔧", verified: true, featured: false, views: 456, rating: 4.6, reviews: 78, seller: "FixIt Kenya", daysAgo: 3, badge: null, tags: ["Licensed", "24/7"] },
  { id: 93, category: "services", title: "Event Planning & Catering", priceLabel: "From KES 20K", location: "Nairobi Wide", description: "Full-service event planning and catering. Weddings, corporate.", image: "🎊", verified: true, featured: false, views: 234, rating: 4.8, reviews: 56, seller: "EventPro Kenya", daysAgo: 7, badge: null, tags: ["Weddings", "Corporate"] },
  { id: 94, category: "services", title: "Digital Marketing", priceLabel: "From KES 15K", location: "Nairobi (Remote)", description: "Complete digital marketing: SEO, PPC, social media.", image: "📱", verified: true, featured: false, views: 234, rating: 4.7, reviews: 45, seller: "DigitalPro", daysAgo: 4, badge: null, tags: ["SEO", "PPC"] },
  { id: 95, category: "services", title: "Architectural & Interior Design", priceLabel: "From KES 25K", location: "Nairobi Wide", description: "Professional architectural and interior design services.", image: "🏗️", verified: true, featured: false, views: 234, rating: 4.9, reviews: 34, seller: "Design Architects", daysAgo: 5, badge: null, tags: ["Architecture", "Interior"] },
  { id: 96, category: "services", title: "Land Surveying", priceLabel: "From KES 10K", location: "Nairobi Wide", description: "Professional land surveying. Boundary surveys, subdivision.", image: "📏", verified: true, featured: false, views: 234, rating: 4.6, reviews: 23, seller: "SurveyPro", daysAgo: 8, badge: null, tags: ["Surveying", "Boundary"] },
  { id: 97, category: "services", title: "Transport & Logistics", priceLabel: "From KES 8K", location: "Nairobi Wide", description: "Transport and logistics. Freight forwarding, warehousing.", image: "🚛", verified: true, featured: false, views: 234, rating: 4.5, reviews: 34, seller: "Logistics Kenya", daysAgo: 6, badge: null, tags: ["Freight", "Warehousing"] },
  { id: 98, category: "services", title: "HR & Recruitment", priceLabel: "From KES 15K", location: "Nairobi (Remote)", description: "HR and recruitment services. Talent acquisition, payroll.", image: "👥", verified: true, featured: false, views: 234, rating: 4.7, reviews: 34, seller: "HR Solutions", daysAgo: 7, badge: null, tags: ["Recruitment", "HR Consulting"] },
  { id: 99, category: "services", title: "Security Services", priceLabel: "From KES 10K", location: "Nairobi Wide", description: "Security services. Manned guarding, CCTV installation.", image: "🛡️", verified: true, featured: false, views: 234, rating: 4.8, reviews: 56, seller: "Secure Kenya", daysAgo: 4, badge: null, tags: ["Guarding", "CCTV"] },
  { id: 100, category: "services", title: "Web Hosting & Domains", priceLabel: "From KES 3K/yr", location: "Nairobi (Remote)", description: "Web hosting, domain registration, SSL certificates.", image: "🌐", verified: true, featured: false, views: 234, rating: 4.6, reviews: 45, seller: "HostPro Kenya", daysAgo: 3, badge: null, tags: ["Hosting", "Domains"] },
  { id: 101, category: "services", title: "Construction Services", priceLabel: "From KES 35K", location: "Nairobi Wide", description: "Construction services. Building, renovation, project management.", image: "🏗️", verified: true, featured: false, views: 234, rating: 4.7, reviews: 34, seller: "Build Kenya", daysAgo: 5, badge: null, tags: ["Construction", "Renovation"] },
  { id: 102, category: "services", title: "Pest Control", priceLabel: "From KES 2K", location: "Nairobi Wide", description: "Professional pest control. Residential and commercial.", image: "🐜", verified: true, featured: false, views: 234, rating: 4.5, reviews: 67, seller: "PestFree Kenya", daysAgo: 6, badge: null, tags: ["Pest Control", "Residential"] },
  { id: 103, category: "services", title: "Car Rental", priceLabel: "From KES 4K/day", location: "Nairobi, Mombasa", description: "Car rental services. Self-drive and chauffeur-driven.", image: "🚗", verified: true, featured: false, views: 234, rating: 4.6, reviews: 45, seller: "RentCar Kenya", daysAgo: 4, badge: null, tags: ["Self-Drive", "Chauffeur"] },
  { id: 104, category: "services", title: "Translation Services", priceLabel: "From KES 1.5K", location: "Nairobi (Remote)", description: "Translation and interpretation. English, French, Swahili.", image: "🌍", verified: true, featured: false, views: 234, rating: 4.8, reviews: 34, seller: "TranslatePro", daysAgo: 8, badge: null, tags: ["Translation", "Interpretation"] },
  { id: 105, category: "services", title: "Insurance Services", priceLabel: "From KES 5K", location: "Nairobi, Mombasa", description: "Insurance services. Motor, health, life, business.", image: "📋", verified: true, featured: false, views: 234, rating: 4.7, reviews: 45, seller: "Insure Kenya", daysAgo: 3, badge: null, tags: ["Motor Insurance", "Health"] },
  // ─── ELECTRONICS (10) ─────────────────────────────────────────────────────────
  { id: 106, category: "electronics", title: "iPhone 15 Pro Max 256GB", priceLabel: "KES 145K", location: "CBD, Nairobi", description: "Brand new, sealed in box. Warranty included.", image: "📱", verified: true, featured: false, views: 1523, rating: 4.5, reviews: 156, seller: "iStore Kenya", daysAgo: 1, badge: "New", tags: ["Sealed", "Warranty"] },
  { id: 107, category: "electronics", title: "Samsung QLED 55\" TV", priceLabel: "KES 85K", location: "Westlands, Nairobi", description: "Samsung QLED 55-inch TV with 4K resolution.", image: "📺", verified: true, featured: false, views: 841, rating: 4.7, reviews: 89, seller: "Electronics Hub", daysAgo: 3, badge: null, tags: ["4K", "Smart TV"] },
  { id: 108, category: "electronics", title: "MacBook Pro M2 2023", priceLabel: "KES 180K", location: "Karen, Nairobi", description: "MacBook Pro M2 chip. 13-inch, 16GB RAM, 512GB SSD.", image: "💻", verified: true, featured: false, views: 789, rating: 4.9, reviews: 23, seller: "MacWorld Kenya", daysAgo: 2, badge: "Featured", tags: ["M2", "16GB RAM"] },
  { id: 109, category: "electronics", title: "PlayStation 5", priceLabel: "KES 75K", location: "Nakuru, Nakuru", description: "Brand new PS5 console with controller. 2-year warranty.", image: "🎮", verified: false, featured: false, views: 1345, rating: 4.6, reviews: 45, seller: "GameHub KE", daysAgo: 6, badge: null, tags: ["New", "Warranty"] },
  { id: 110, category: "electronics", title: "Dell XPS 13 2024", priceLabel: "KES 160K", location: "Mombasa, Mombasa", description: "Dell XPS 13 with Intel i7, 16GB RAM, 512GB SSD.", image: "💻", verified: true, featured: false, views: 456, rating: 4.8, reviews: 34, seller: "Dell Kenya", daysAgo: 5, badge: null, tags: ["i7", "16GB"] },
  { id: 111, category: "electronics", title: "AirPods Pro 2", priceLabel: "KES 28K", location: "CBD, Nairobi", description: "Brand new AirPods Pro 2. Noise cancellation, spatial audio.", image: "🎧", verified: true, featured: false, views: 234, rating: 4.7, reviews: 56, seller: "Apple Kenya", daysAgo: 2, badge: "New", tags: ["Sealed", "Noise Cancelling"] },
  { id: 112, category: "electronics", title: "Samsung Galaxy S24", priceLabel: "KES 120K", location: "Westlands, Nairobi", description: "Brand new Samsung Galaxy S24. 128GB. Sealed box.", image: "📱", verified: true, featured: false, views: 345, rating: 4.8, reviews: 67, seller: "Samsung Store", daysAgo: 1, badge: "New", tags: ["Sealed", "Warranty"] },
  { id: 113, category: "electronics", title: "Lenovo ThinkPad X1", priceLabel: "KES 150K", location: "Nairobi", description: "Lenovo ThinkPad X1. Intel i7, 16GB RAM, 512GB SSD.", image: "💻", verified: true, featured: false, views: 234, rating: 4.7, reviews: 34, seller: "Lenovo Kenya", daysAgo: 4, badge: null, tags: ["i7", "Lightweight"] },
  { id: 114, category: "electronics", title: "iPad Pro 12.9 M2", priceLabel: "KES 120K", location: "CBD, Nairobi", description: "iPad Pro 12.9 with M2 chip. 256GB. Wi-Fi + Cellular.", image: "📱", verified: true, featured: false, views: 234, rating: 4.8, reviews: 45, seller: "Apple Kenya", daysAgo: 3, badge: null, tags: ["M2", "Cellular"] },
  { id: 115, category: "electronics", title: "Bose QuietComfort Headphones", priceLabel: "KES 35K", location: "Westlands, Nairobi", description: "Bose QuietComfort headphones. Noise cancelling. Premium sound.", image: "🎧", verified: true, featured: false, views: 234, rating: 4.9, reviews: 56, seller: "Audio Kenya", daysAgo: 2, badge: "New", tags: ["Noise Cancelling", "Wireless"] },
  // ─── AGRICULTURE (10) ─────────────────────────────────────────────────────────
  { id: 116, category: "agriculture", title: "2-Acre Farm – Limuru", priceLabel: "KES 1.2M", location: "Limuru, Kiambu", description: "2-acre fertile farm land. Title deed ready. Good rainfall.", image: "🌱", verified: true, featured: false, views: 803, rating: 4.9, reviews: 7, seller: "Kiambu Land Agency", daysAgo: 7, badge: null, tags: ["Title Deed", "Fertile"] },
  { id: 117, category: "agriculture", title: "Greenhouse Farm – Nanyuki", priceLabel: "KES 2.8M", location: "Nanyuki, Laikipia", description: "Greenhouse farm with 3 acres under cultivation.", image: "🌿", verified: true, featured: false, views: 492, rating: 4.7, reviews: 15, seller: "Nanyuki Farm Solutions", daysAgo: 4, badge: "Featured", tags: ["Greenhouse", "Water Source"] },
  { id: 118, category: "agriculture", title: "1-Acre Tea Land – Kericho", priceLabel: "KES 850K", location: "Kericho, Kericho", description: "Tea-growing land with mature bushes. Good returns.", image: "🍃", verified: true, featured: false, views: 367, rating: 4.5, reviews: 9, seller: "Kericho Lands", daysAgo: 10, badge: null, tags: ["Tea", "Mature Bushes"] },
  { id: 119, category: "agriculture", title: "Dairy Farm – 10 Cows", priceLabel: "KES 2.2M", location: "Nakuru, Nakuru", description: "Dairy farm with 10 cows and milking equipment.", image: "🐄", verified: true, featured: false, views: 256, rating: 4.6, reviews: 12, seller: "Nakuru Dairy", daysAgo: 8, badge: null, tags: ["Dairy", "Equipment"] },
  { id: 120, category: "agriculture", title: "Poultry Farm – 300 Birds", priceLabel: "KES 1.1M", location: "Thika, Kiambu", description: "Poultry farm with 300 layers. Equipment included.", image: "🐔", verified: true, featured: false, views: 234, rating: 4.5, reviews: 9, seller: "Thika Poultry", daysAgo: 9, badge: null, tags: ["Layers", "Equipment"] },
  { id: 121, category: "agriculture", title: "Fish Farm – 2 Ponds", priceLabel: "KES 980K", location: "Kisumu, Kisumu", description: "Fish farm with 2 ponds. Tilapia farming. Equipment included.", image: "🐟", verified: true, featured: false, views: 234, rating: 4.4, reviews: 7, seller: "Kisumu Fish Farm", daysAgo: 10, badge: null, tags: ["Tilapia", "Ponds"] },
  { id: 122, category: "agriculture", title: "Coffee Farm – 2 Acres", priceLabel: "KES 2.5M", location: "Kiambu, Kiambu", description: "Coffee farm with 2 acres of mature coffee bushes.", image: "☕", verified: true, featured: false, views: 234, rating: 4.6, reviews: 8, seller: "Kiambu Coffee", daysAgo: 6, badge: null, tags: ["Coffee", "Mature"] },
  { id: 123, category: "agriculture", title: "10-Acre Mixed Farm", priceLabel: "KES 2.0M", location: "Nakuru, Nakuru", description: "10-acre land suitable for mixed farming. Good soil.", image: "🌾", verified: true, featured: false, views: 234, rating: 4.5, reviews: 6, seller: "Nakuru Lands", daysAgo: 11, badge: null, tags: ["Mixed Farming", "Water Access"] },
  { id: 124, category: "agriculture", title: "Organic Farm – 3 Acres", priceLabel: "KES 1.8M", location: "Limuru, Kiambu", description: "Organic farm with 3 acres. Vegetables and herbs.", image: "🥬", verified: true, featured: false, views: 234, rating: 4.7, reviews: 9, seller: "Organic Farms", daysAgo: 7, badge: null, tags: ["Organic", "Vegetables"] },
  { id: 125, category: "agriculture", title: "Equine Farm – 3 Horses", priceLabel: "KES 3.2M", location: "Nanyuki, Laikipia", description: "Horse farm with 3 horses and stables.", image: "🐴", verified: true, featured: false, views: 234, rating: 4.8, reviews: 7, seller: "Nanyuki Horses", daysAgo: 4, badge: "Featured", tags: ["Horses", "Stables"] },
  // ─── FASHION (8) ──────────────────────────────────────────────────────────────
  { id: 126, category: "fashion", title: "Boutique Stock – Ladies", priceLabel: "KES 35K/lot", location: "Eastleigh, Nairobi", description: "Wholesale ladies dresses, tops, skirts. 150 pieces per lot.", image: "👗", verified: false, featured: false, views: 241, rating: 4.2, reviews: 34, seller: "Eastleigh Fashions", daysAgo: 4, badge: null, tags: ["Wholesale", "150pcs"] },
  { id: 127, category: "fashion", title: "African Wear Collection", priceLabel: "From KES 12K", location: "Mombasa, Mombasa", description: "High-quality African fashion designs. Kitenge, Kente.", image: "👘", verified: true, featured: false, views: 356, rating: 4.8, reviews: 56, seller: "African Couture", daysAgo: 2, badge: "New", tags: ["Custom", "African Prints"] },
  { id: 128, category: "fashion", title: "Shoe Store Stock", priceLabel: "KES 80K/lot", location: "CBD, Nairobi", description: "Wholesale shoes - 250 pairs. Various styles.", image: "👟", verified: false, featured: false, views: 189, rating: 4.0, reviews: 23, seller: "ShoeWorld KE", daysAgo: 8, badge: null, tags: ["Wholesale", "250 Pairs"] },
  { id: 129, category: "fashion", title: "Custom Suits Business", priceLabel: "KES 580K", location: "Westlands, Nairobi", description: "Tailoring business with equipment and fabric stock.", image: "👔", verified: true, featured: false, views: 234, rating: 4.7, reviews: 34, seller: "TailorMade KE", daysAgo: 11, badge: null, tags: ["Equipment", "Customer Base"] },
  { id: 130, category: "fashion", title: "Designer Handbags Lot", priceLabel: "KES 55K/lot", location: "Eastleigh, Nairobi", description: "Wholesale designer handbags. 40 pieces per lot.", image: "👜", verified: false, featured: false, views: 134, rating: 4.3, reviews: 23, seller: "Eastleigh Bags", daysAgo: 6, badge: null, tags: ["Wholesale", "40pcs"] },
  { id: 131, category: "fashion", title: "Kids Clothing Lot", priceLabel: "KES 25K/lot", location: "CBD, Nairobi", description: "Wholesale kids clothing. 80 pieces per lot.", image: "👶", verified: false, featured: false, views: 134, rating: 4.1, reviews: 12, seller: "Kids Fashion", daysAgo: 7, badge: null, tags: ["Wholesale", "80pcs"] },
  { id: 132, category: "fashion", title: "Sportswear Bulk", priceLabel: "KES 45K/lot", location: "Mombasa, Mombasa", description: "Wholesale sportswear. 100 pieces per lot.", image: "🏃", verified: false, featured: false, views: 134, rating: 4.2, reviews: 18, seller: "Sportswear KE", daysAgo: 5, badge: null, tags: ["Wholesale", "Sportswear"] },
  { id: 133, category: "fashion", title: "Evening Wear Custom", priceLabel: "From KES 18K", location: "Westlands, Nairobi", description: "Designer evening wear. Custom made. High quality.", image: "👗", verified: true, featured: false, views: 134, rating: 4.8, reviews: 34, seller: "Evening Couture", daysAgo: 3, badge: null, tags: ["Custom", "Designer"] },
  // ─── EDUCATION (4) ─────────────────────────────────────────────────────────────
  { id: 134, category: "education", title: "Pre-School – Karen", priceLabel: "KES 2.8M", location: "Karen, Nairobi", description: "Established pre-school with 40 students. Good reputation.", image: "🏫", verified: true, featured: false, views: 478, rating: 4.9, reviews: 11, seller: "Little Scholars", daysAgo: 5, badge: "Featured", tags: ["Franchise", "Established"] },
  { id: 135, category: "education", title: "Online Tutoring", priceLabel: "From KES 2K/hr", location: "Nairobi (Remote)", description: "Online tutoring in Math, Sciences, Languages.", image: "📚", verified: true, featured: false, views: 345, rating: 4.7, reviews: 45, seller: "TutorKenya", daysAgo: 3, badge: null, tags: ["Online", "All Levels"] },
  { id: 136, category: "education", title: "Music School – Westlands", priceLabel: "KES 1.8M", location: "Westlands, Nairobi", description: "Music school with 60 students. Good reputation.", image: "🎵", verified: true, featured: false, views: 234, rating: 4.7, reviews: 9, seller: "Music Academy", daysAgo: 6, badge: null, tags: ["Music", "Established"] },
  { id: 137, category: "education", title: "Language Institute – Mombasa", priceLabel: "KES 2.0M", location: "Mombasa, Mombasa", description: "Language institute teaching English and French.", image: "🌍", verified: true, featured: false, views: 234, rating: 4.6, reviews: 8, seller: "Language Institute", daysAgo: 7, badge: null, tags: ["Languages", "Established"] },
  // ─── HEALTHCARE (4) ────────────────────────────────────────────────────────────
  { id: 138, category: "healthcare", title: "Dental Clinic Equipment", priceLabel: "KES 1.8M", location: "Westlands, Nairobi", description: "Complete dental clinic equipment. 2 chairs, X-ray.", image: "🦷", verified: true, featured: false, views: 234, rating: 4.5, reviews: 6, seller: "Dental Supply KE", daysAgo: 12, badge: null, tags: ["Complete", "Well Maintained"] },
  { id: 139, category: "healthcare", title: "Pharmacy – Nakuru", priceLabel: "KES 3.2M", location: "Nakuru, Nakuru", description: "Established pharmacy. Stock worth KES 800K included.", image: "💊", verified: true, featured: false, views: 456, rating: 4.3, reviews: 9, seller: "Nakuru Pharmacy", daysAgo: 7, badge: null, tags: ["Established", "Stock Included"] },
  { id: 140, category: "healthcare", title: "Medical Clinic – Mombasa", priceLabel: "KES 2.5M", location: "Mombasa, Mombasa", description: "Established clinic. 2 consultation rooms. Good location.", image: "🏥", verified: true, featured: false, views: 234, rating: 4.6, reviews: 8, seller: "Mombasa Clinic", daysAgo: 8, badge: null, tags: ["Established", "Ready"] },
  { id: 141, category: "healthcare", title: "Physiotherapy Centre", priceLabel: "KES 1.5M", location: "Nairobi", description: "Physiotherapy centre with equipment. 3 years operation.", image: "💪", verified: true, featured: false, views: 234, rating: 4.7, reviews: 12, seller: "Physio Centre", daysAgo: 5, badge: null, tags: ["Equipment", "Established"] },
  // ─── PRODUCTS (9) ──────────────────────────────────────────────────────────────
  { id: 142, category: "products", title: "Bulk Coffee – Premium", priceLabel: "KES 6K/50kg", location: "Kiambu, Kiambu", description: "High-quality Kenyan coffee beans. Direct from farm.", image: "☕", verified: true, featured: false, views: 234, rating: 4.9, reviews: 34, seller: "Kiambu Coffee", daysAgo: 2, badge: null, tags: ["Premium", "Direct Farm"] },
  { id: 143, category: "products", title: "Furniture Manufacturing", priceLabel: "KES 2.0M", location: "Thika, Kiambu", description: "Furniture manufacturing with equipment and showroom.", image: "🪑", verified: true, featured: false, views: 589, rating: 4.7, reviews: 23, seller: "Thika Furniture", daysAgo: 4, badge: "Featured", tags: ["Equipment", "Showroom"] },
  { id: 144, category: "products", title: "Bulk Honey – 500kg", priceLabel: "KES 650K", location: "Nakuru, Nakuru", description: "Pure organic honey. 500kg available. Direct from farm.", image: "🍯", verified: true, featured: false, views: 234, rating: 4.8, reviews: 23, seller: "Honey Farms", daysAgo: 3, badge: null, tags: ["Organic", "Bulk"] },
  { id: 145, category: "products", title: "Bulk Maize – 100 Bags", priceLabel: "KES 250K", location: "Eldoret, Uasin Gishu", description: "100 bags of high-quality maize. Direct from farm.", image: "🌽", verified: true, featured: false, views: 234, rating: 4.5, reviews: 12, seller: "Eldoret Farms", daysAgo: 5, badge: null, tags: ["Bulk", "Maize"] },
  { id: 146, category: "products", title: "Bulk Avocados – 300kg", priceLabel: "KES 220K", location: "Kiambu, Kiambu", description: "300kg of Haas avocados. Direct from farm.", image: "🥑", verified: true, featured: false, views: 234, rating: 4.6, reviews: 15, seller: "Avocado Farms", daysAgo: 4, badge: null, tags: ["Haas", "Bulk"] },
  { id: 147, category: "products", title: "Bulk Soap – 500 Pieces", priceLabel: "KES 120K", location: "Nairobi", description: "500 pieces of quality soap. Various scents.", image: "🧼", verified: true, featured: false, views: 234, rating: 4.3, reviews: 12, seller: "Soap Factory", daysAgo: 6, badge: null, tags: ["Bulk", "Wholesale"] },
  { id: 148, category: "products", title: "Bulk Cooking Oil – 500L", priceLabel: "KES 180K", location: "Mombasa, Mombasa", description: "500 litres of quality cooking oil.", image: "🫒", verified: true, featured: false, views: 234, rating: 4.4, reviews: 9, seller: "Oil Suppliers", daysAgo: 7, badge: null, tags: ["Bulk", "Cooking Oil"] },
  { id: 149, category: "products", title: "Bulk Sugar – 100 Bags", priceLabel: "KES 230K", location: "Kisumu, Kisumu", description: "100 bags of sugar. Good quality.", image: "🍬", verified: true, featured: false, views: 234, rating: 4.5, reviews: 8, seller: "Sugar Suppliers", daysAgo: 8, badge: null, tags: ["Bulk", "Sugar"] },
  { id: 150, category: "products", title: "Bulk Flour – 50 Bags", priceLabel: "KES 120K", location: "Nairobi", description: "50 bags of quality flour. Wholesale pricing.", image: "🌾", verified: true, featured: false, views: 234, rating: 4.4, reviews: 10, seller: "Flour Suppliers", daysAgo: 3, badge: null, tags: ["Bulk", "Flour"] },
];

// ─── MOBILE MENU ────────────────────────────────────────────────────────────
function toggleMenu() {
  const menu = document.getElementById('mobileMenu');
  if (menu) menu.classList.toggle('active');
}

// ─── LOCATION ROTATOR ────────────────────────────────────────────────────────
let locationIndex = 0;
if (document.getElementById('locationDisplay')) {
  setInterval(() => {
    locationIndex = (locationIndex + 1) % LOCATIONS.length;
    document.getElementById('locationDisplay').textContent = LOCATIONS[locationIndex];
  }, 2000);
}

// ─── RENDER CATEGORIES ──────────────────────────────────────────────────────
function renderCategories() {
  const grid = document.getElementById('categoriesGrid');
  if (!grid) return;

  grid.innerHTML = CATEGORIES.map(cat => `
    <div class="category-card" onclick="location.href='browse.html?category=${cat.id}'">
      <div class="icon">${cat.icon}</div>
      <div class="name">${cat.label}</div>
      <div class="count">${cat.count.toLocaleString()}</div>
    </div>
  `).join('');
}

// ─── RENDER LISTINGS ──────────────────────────────────────────────────────
function renderListings() {
  const grid = document.getElementById('listingsGrid');
  if (!grid) return;

  const featured = LISTINGS.filter(l => l.featured).slice(0, 8);

  grid.innerHTML = featured.map(l => {
    const stars = '★'.repeat(Math.round(l.rating)) + '☆'.repeat(5 - Math.round(l.rating));
    const badgeHtml = l.badge ? `<span class="badge ${getBadgeClass(l.badge)}">${l.badge}</span>` : '';
    const verifiedHtml = l.verified ? `<span class="badge badge-green">✓ Verified</span>` : '';
    const daysText = l.daysAgo === 0 ? 'Today' : `${l.daysAgo}d ago`;

    return `
      <div class="listing-card" onclick="location.href='listing.html?id=${l.id}'">
        <div class="listing-image">
          ${l.image}
          ${badgeHtml}
          ${l.featured ? '<div class="featured-star">⭐</div>' : ''}
          <div class="view-count">👁 ${l.views.toLocaleString()}</div>
        </div>
        <div class="listing-body">
          <div style="display:flex;align-items:center;gap:6px;margin-bottom:8px;">
            <span class="badge badge-green" style="font-size:10px;">${CATEGORIES.find(c => c.id === l.category)?.label || l.category}</span>
            ${verifiedHtml}
          </div>
          <h3>${l.title}</h3>
          <div class="desc">${l.description}</div>
          <div class="price">${l.priceLabel}</div>
          <div class="meta">
            <span>📍 ${l.location}</span>
            <div>
              <span class="stars">${stars}</span>
              <span>(${l.reviews})</span>
            </div>
          </div>
        </div>
        <div class="listing-footer">
          <div class="seller">
            <div class="avatar">${l.seller.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase()}</div>
            <span>${l.seller}</span>
          </div>
          <span class="days">${daysText}</span>
        </div>
      </div>
    `;
  }).join('');
}

function getBadgeClass(badge) {
  const map = { 'Featured': 'badge-saffron', 'Hot': 'badge-red', 'Urgent': 'badge-red', 'New': 'badge-blue' };
  return map[badge] || 'badge-green';
}

// ─── INIT ────────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  renderCategories();
  renderListings();
});
